### ISSUE TITLE
Download image is oddly cropped

### ISSUE THREAD

**Issue by egpbos** [common-workflow-language/cwlviewer#47] opened 2017-02-16 12:51 UTC
Thank you for your great tool, you rock!

However ;)

On this view: https://view.commonwl.org/workflows/github.com/nlesc-sherlock/deeplearning/tree/161ad0315be11f1dd4ba605d7bf0168002f434b8/CWLworkflow

When downloading the image it looks like this:

![workflow](https://cloud.githubusercontent.com/assets/6146598/23021961/e4aafff4-f44e-11e6-9f6d-d1a9f519f687.png)

**Comment by MarkRobbo** [comment] 2017-02-17 12:20
Thanks for the issue, this seems to be an caused by the moving/zooming of the svg in combination with the method that images are generated.

I am planning to move the Graphviz dot graph rendering to the back end to increase rendering speed and this will have the side effect of providing a permalink to image downloads rather than generating them clientside and fixing this particular bug.

**Comment by MarkRobbo** [comment] 2017-02-22 15:12
Fixed by #51

**Closed by MarkRobbo** 2017-02-22 15:12 UTC
Labels: bug
